### ISSUE TITLE
Incorrect code for quote-mode DEL

### ISSUE THREAD

**Issue by mist64** [gardners/open-roms#39]
If you type the following:

    ?ASC("")

Then navigate between the "" and type

    <INST><DEL>

The character that shows up is an reverse semicolon. The result of the expression is 187.

Instead, a reverse T should show up, and the result should be 20.

**Comment by FeralChild64** [comment]
Character printed is now fixed in my branch (https://github.com/FeralChild64/open-roms/commit/dea993e4b72b1ca57cb6b05f01eefcf5e75a5df8) - I didn't notice the .A got overridden at some point of this flow. 

But the ASC result is still incorrect (148 now). Probably the original CHRIN (_chrin_enter_loop_ in our code) does some kind of translation which is not implemented in Open ROMs. This will need more in-depth investigation.

[edit] Probably _screen_code_to_petscii_ routine needs to be checked, possibly we should implement this table: https://sta.c64.org/cbm64scrtopetext.html

**Comment by FeralChild64** [comment]
Commit https://github.com/FeralChild64/open-roms/commit/af1f5b079d885bb5cbf7898ab7e18c47056c664a (together with previous one) should fix the issue.

BTW. Thanks for all the remarks!

**Comment by FeralChild64** [comment]
Problem fixed in the commit mentioned above.
